### ISSUE TITLE
Questions: exclude links and programmatically navigate

### ISSUE THREAD

**Issue by davidelanfranchi** [Dogstudio/highway#10]
Hello,
thanks for this new library!
I was doing some tests with Highway and I would like to ask a few questions.

In my experience with Barba I found useful the opportunity to exclude some links from the transition manager behaviour. This was needed, for example, in case of download links or just to navigate to some pages.
I understand that Highway, by design, “just works”, but maybe you can think about adding an option to exclude some link.

The exclusion could depend, for example, from an html attribute.
Otherwise, it could be useful an event fired before the navigation, in which we could test the clicked element and decide to override the default behaviour.
This event could be useful in general, for example to store the last clicked element in a variable.

Another useful addition could be the opportunity to programmatically navigate to an URL.
This functionality could be useful in case we have to prevent the normal behaviour to do something, for example animate an overlay, or redirect after an AJAX submission.

Thanks again!

**Comment by Anthodpnt** [comment]
Hi @davidelanfranchi,

About the feature to disable Highway on some links you can simply use a `target` attribute set to `self` so that Highway knows you want to skip transitions and hard-reload the page... So there is no need to add options or custom attributes because HTML already provide the `target="_self"` attribute that tells the browser and Highway to keep the default behaviour of the link and open the page in the same window with hard-reload.

We'll try to document this ASAP...

Concerning the event fired before the navigation you can use the `NAVIGATE_OUT` event that is fired right after a link is clicked... However I cannot see why you would need to know which link is clicked but we have an [**example**](https://github.com/Dogstudio/highway/blob/master/examples/basic-menu-active/src/index.js) using events to check the active link in a menu and change its classname based on the URL visited. It uses the `NAVIGATE_IN` event for some purposes but you should get the idea...

For the last point I don't really get the idea... I understand the concept of having a method to trigger a navigation to an URL using JS but what do you mean by _animating and overlay_ ? About the AJAX submission or forms submissions in general I think you should keep the default hard-reload behaviour IMO and avoid transitions for this kind of interactions... Anyway with a good use case this feature might be useful but for now we don't have one so we'll keep it in mind and come back to it if needed in the right time...

Thanks for your feedbacks mate !
Anthodpnt
