### ISSUE TITLE
Add options for error pages

### ISSUE THREAD

**Issue by TristanPct** [Dogstudio/highway#12]
Hello, it's me again 😄 

For the moment when Highway encounter an error page (404, 500...) it sends the NAVIGATE_ERROR event but doesn't try to load the page (event if this page have a `router-view`).

Is it planned to add an option to load error pages likes other pages ?

For the moment an alternative is to tell the error page to have an HTTP 200 code rather than error code if `X-Requested-With: Highway` header is present.

**Comment by Anthodpnt** [comment]
Hi @TristanPct ,

We are currently working on the v2.0 of **Highway**...

We have add a new method called `location` to `Highway.Core` that'll give you the ability to redirect to a page like you would do with `window.location` but using **Highway**.

So I would say that since the `NAVIGATE_ERROR` event gives you acces to the HTTP/Request status, you'll be able to know the status code and use this method to redirect to the right error page using this new method. What do you think ?

Cheers,
Anthodpnt

**Comment by Anthodpnt** [comment]
@TristanPct We juste released the v2.0.0 of Highway that will fix your issue. Since we cannot predict that there will be an error or that an error page is provided we have to hard reload the page as soon as the `response.status` of the HTTPRequest is outside the 200-299 range.

Best regards,
Anthodpnt
