### ISSUE TITLE
Wordpress search results problem

### ISSUE THREAD

**Issue by wezzou1** [Dogstudio/highway#23]
Hi! 

I'm using wordpress and highway on my site, but when I search on my page, the searchresults display's as normal, but something seems to be off, when I'm clicking at my logotype  (Go back to start) the transition is running and the route-view change as it should, But the content dosen't change? what can be problem here?

The url be like **name.localhost/?s=mysearch&post_type=product**

**Comment by ThaoD5** [comment]
Hello @wezzou1, we came across the same issue (search results on homepage with a wordpress website) on our last production at Dogstudio, we plan to have a look at it as soon as possible in order to understand precisely what is going on and why this is happening.

We will keep this issue updated with the results of our investigation and ping you on the response as soon as we get there :-)

Hope you're enjoying Highway !

Thao

**Comment by ThaoD5** [comment]
@wezzou1 We just had a look and it was indeed the caching of the pages that was not enough precise concerning the name of the page to be cached

We fixed this issue in latest version [v2.0.2](https://github.com/Dogstudio/highway/releases/tag/v2.0.2) 
 that is now released, we tested the fix on the concerned last production, and it now works like a charm.

Can you confirm us that you do not have any trouble with this anymore ?

Don't hesitate to send us the site you're making using Highway, we're always interested in sharing them in the [demo page](https://dogstudio.github.io/highway/demos.html)

Thao

**Comment by wezzou1** [comment]
@ThaoD5 Thank you for a quick fix! you are the best! It's working like a charm! :) 💯 👍

**Comment by wezzou1** [comment]
@ThaoD5 Oh, i forgot, if you wanna see what i'm working on you can check it out at [http://norrlands.dev.fmca.se/](http://norrlands.dev.fmca.se/)

**Comment by ThaoD5** [comment]
@wezzou1 Ah yes, I already saw it because you opened another issue previously :-) 
Glad to see everything goes smoothly 👍
