### ISSUE TITLE
Starter Kit

### ISSUE THREAD

**Issue by artyprog** [Dogstudio/highway#35]
Hello,

Could you put a simple starter project  for HighWay ?
In fact I would like to create  a static site with it .

Regards

**Comment by ThaoD5** [comment]
Hello @artyprog 

We worked on the documentation so that it is clear and useable by anyone with the specifications of anyone, by providing a starter project, we then have to make choices that are not ours to make ( using gulp / webpack / ... to compile for example )

We keep the idea in mind and we will probably setup some examples on codepen later on, but providing static starter setups is really not in our list of high priorities :)

Have a great day,

Thao
