### ISSUE TITLE
this.properties.view doesn't refer to the actual DOM

### ISSUE THREAD

**Issue by thiervoj** [Dogstudio/highway#46]
Hi !

I need to attach events to some children of my view.
I used to do that by getting my renderer's children using `this.view.querySelector(...)` on earlier versions of highway (up to 2.0.8).

Since 2.1.0, `this.properties.view` refers to a clone of the actual element. So to get the real DOM element I had to add at the very start of my Renderers' `onEnter` function the following line :
```
this.properties.view = this.wrap.lastElementChild
```

After searching in your code, I found two things causing problems in my case :
- In `core.js` https://github.com/Dogstudio/highway/blob/eff45aea4c980010264f389572c2d37bf21aec24/src/core.js#L31 the document node is cloned so the view is not the one in the DOM
- In `renderer.js` https://github.com/Dogstudio/highway/blob/eff45aea4c980010264f389572c2d37bf21aec24/src/renderer.js#L37 adding an element with this function creates a "duplicate" of the source element (`this.properties.view` becomes a clone)

Maybe I'm doing something wrong about it and I'm not using the correct properties/functions to get the current view ?

Anyway, thanks for this great lib 😄 

Jordan

**Comment by Anthodpnt** [comment]
Hi @thiervoj,

Since the v2.1.0 I would recommend to use `this.wrap.lastElementChild` to get the `data-router-view` that has been added to the DOM. The `this.properties.view` value is only used internally to send the right view with the events but is not recommended to be used to select children elements of the `data-router-view`.

https://github.com/Dogstudio/highway/blob/6b4627dd414c4be9948907c8593e343c319d7c45/src/core.js#L284-L291

For the lines you spotted in Highway's source code, they are right and have their purpose.

Best regards,
Anthodpnt

**Comment by thiervoj** [comment]
Ok thanks, I will continue to use `this.wrap.lastElementChild` 👍
