### ISSUE TITLE
Class constructor Renderer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by wassim** [Dogstudio/highway#6]
Hi, I followed your basic installation guide but I'm getting the following browser error:

`Uncaught TypeError: Class constructor Renderer cannot be invoked without 'new'`

Any ideas where this could come from? Btw I'm using buble for compiling js.

**Comment by Anthodpnt** [comment]
Hi @wassim,

Highway comes in ES6 and I pretty sure it's not compiled through babel maybe because you are ignoring the `node_modules` which result in your code being compiled in ES5 mixed with Highway that remains in ES6.

Please check out the [**basic-polyfill**](https://github.com/Dogstudio/highway/blob/master/examples/basic-polyfill/webpack.config.js) example that should help you change your configuration in order to include Highway in the compilation process. This is an example using the `babel-loader` through Webpack.

This is our will to keep Highway in ES6 but we will consider providing an ES5 version to avoid this kind of repetitive issues 😃. Until then please keep us informed if this solution fixed your issue.

Best regards,
Anthodpnt

**Comment by wassim** [comment]
@Anthodpnt thanks. Indeed I was ignoring the node_modules/@dogstudio. Now eslint isn't happy 😭

```
error  in ./node_modules/@dogstudio/highway/dist/highway.js

Module build failed:
232 :    *
233 :    * @return {object} Promise
234 :    */
235 :   show() {
236 :     return new Promise(async resolve => {
                                   ^
Unexpected token (236:29) 
```

I saw that you are using eslint as well, are you linting successfully?

**Comment by Anthodpnt** [comment]
@wassim 

I don't know how you configured your `.eslintrc` file but apparently it doesn't support async/await and returns errors. Maybe you should consider changing the `ecmaVersion` to `2018` or checkout the configuration we have for Highway.

**Comment by wassim** [comment]
Couldn't pass through the multiple errors I'm getting. Would love to see a compiled es5 version.

**Comment by Anthodpnt** [comment]
@wassim 

I'm happy to announce that the latest release [**v1.3.6**](https://github.com/Dogstudio/highway/releases/tag/v1.3.6) now provides an ES5 version of Highway.
Please give it a try and keep us informed about your issue.

Best regards,
Anthodpnt

**Comment by wassim** [comment]
Thanks! Working nice now 👌

**Comment by Anthodpnt** [comment]
Perfect ! Closing the issue then...
