### ISSUE TITLE
ES5 docs and examples?

### ISSUE THREAD

**Issue by aolko** [Dogstudio/highway#60]
Hi there,
Please provide ES5 specific docs and examples, since it has none of those imports, extends and whatnots. Thanks for taking a look.

Also, any examples on integrating it with GSAP?

**Comment by Anthodpnt** [comment]
Hello @aolko,

Please learn to say _Hello_ and _Thank you_ and we'll then see if we can help you...

Best regards,
Anthodpnt

**Comment by aolko** [comment]
> Hello @aolko,
> 
> Please learn to say _Hello_ and _Thank you_ and we'll then see if we can help you...
> 
> Best regards,
> Anthodpnt

Well, that was anticlimactic, still edited.

**Comment by Anthodpnt** [comment]
Hello @aolko,

There is no point for us to provide ES5 documentation because Highway is not meant to be used in ES5 which is part of its modern approach to make it more light, flexible and efficient. About the examples integrating GSAP, there are already available on the website. Please take a look at them:

https://highway.js.org/examples/transitions.html

Best regards,
Anthodpnt

**Comment by aolko** [comment]
Pardon, but you are contradicting your own docs:
![](https://i.imgur.com/ASzoO4U.png)
Even if it's compiled, it still should be documented properly.

**Comment by Anthodpnt** [comment]
You're totally right, that might be a bit confusing. We have a version already built from ES6 to ES5 but in order to use Highway you will have to use ES6 sugar syntax.

We'll work on a better explanation of this part of the documentation.
