### ISSUE TITLE
kill/destroy class declarations?

### ISSUE THREAD

**Issue by vishalp36** [Dogstudio/highway#89]
SOS
I want to kill/destroy gsap animations from new Home();

```
import Home from "home/home";
let home = undefined;
class HomeTransition extends Highway.Transition {
	
	in ({ from, to, done }) {
		from.remove();
		home = new Home();
		done();

	}

	out({ from, done }) {
		home = undefined;
		done();
	}
}
```

**Comment by Anthodpnt** [comment]
Hey @vishalp36!

We have to close this issue because it isn't related to Highway. We recommend you to join the [**Slack community**](https://join.slack.com/t/highway-lib/shared_invite/zt-60jkz5kh-defbgkYYTclu609sUAEN3Q) for this kind of requests. We'll be happy to review this issue related to your source code on Slack. Let's keep the _Issues_ section for Highway-only issues.

Thanks,
Anthodpnt
